# Generated by Django 4.2.20 on 2025-08-01 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0002_rename_fecha_cierre_prestamo_fechacierre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='montoInicial',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='saldoActual',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
    ]
