# Generated by Django 4.2.20 on 2025-08-20 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_estado'),
        ('prestamos', '0003_alter_prestamo_montoinicial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='fiador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos_como_fiador', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='interesesPendientesIniciales',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Intereses acumulados antes de registrar el préstamo en el sistema', max_digits=10),
        ),
    ]
