# Generated by Django 4.2.20 on 2025-08-20 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0004_prestamo_fiador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='notas',
            field=models.TextField(blank=True, help_text='Información adicional o comentarios sobre el préstamo', null=True),
        ),
    ]
