# Generated by Django 4.2.20 on 2025-09-13 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inversionistas', '0001_initial'),
        ('prestamos', '0005_prestamo_notas'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='inversionista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos', to='inversionistas.inversionista'),
        ),
    ]
