# Generated by Django 4.2.20 on 2025-04-09 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_alter_pago_fecha_pago'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pago',
            old_name='fecha_pago',
            new_name='fechaPago',
        ),
    ]
