# Generated by Django 4.2.20 on 2025-04-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobro',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
