# Generated by Django 4.2.20 on 2025-04-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0003_cobro_fecha_pago_cobro_monto_pagado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobro',
            name='fecha_generacion',
            field=models.DateField(),
        ),
    ]
