# Generated by Django 4.2.20 on 2025-04-09 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0004_alter_cobro_fecha_generacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cobro',
            old_name='fecha_generacion',
            new_name='fechaGeneracion',
        ),
        migrations.RenameField(
            model_name='cobro',
            old_name='fecha_pago',
            new_name='fechaPago',
        ),
        migrations.RenameField(
            model_name='cobro',
            old_name='fecha_vencimiento',
            new_name='fechaVencimiento',
        ),
        migrations.RenameField(
            model_name='cobro',
            old_name='monto_interes',
            new_name='montoInteres',
        ),
        migrations.RenameField(
            model_name='cobro',
            old_name='monto_pagado',
            new_name='montoPagado',
        ),
    ]
