# Generated by Django 4.2.20 on 2025-04-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('activos', 'Préstamos Activos'), ('pendientes', 'Pagos Pendientes'), ('intereses', 'Intereses Generados'), ('pagados', 'Préstamos Pagados')], max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('datos', models.JSONField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['tipo'], name='reportes_re_tipo_1e0f0e_idx'), models.Index(fields=['fecha_inicio', 'fecha_fin'], name='reportes_re_fecha_i_dae18e_idx')],
            },
        ),
    ]
