# Generated by Django 4.2.20 on 2025-04-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_rename_fecha_registro_cliente_fechacreacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(default='Activo', max_length=10),
        ),
    ]
